services:
  sonarrhd:
    container_name: sonarrhd
    image: ghcr.io/hotio/sonarr
    networks:
      - docker_default
    ports:
      - "8988:8989"
    environment:
      PUID: '$PUID'
      PGID: '$PGID'
      UMASK: '$UMASK'
      TZ: '$TZ'
    volumes:
      - '$WORKDIR/sonarrhd:/config'
      - '$DATADIR'

networks:
  docker_default:
    external: true
