services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    networks:
      - docker_default
    ports:
      - '4000:80' # Public HTTP Port. Port Forwarding on Router is ON.
    volumes:
      - /opt/config/dashy:/config
#      - /opt/config/dashy/assets/my-config.yml:/app/public/conf.yml
#      - /opt/config/dashy/assets/item-icons:/app/public/item-icons
    environment:
      NODE_ENV: 'production'
      TZ: 'Europe/Stockholm'
      PUID: '1000'
      PGID: '1000'

networks:
  docker_default:
    external: true
