services:
  metube:
    container_name: metube
    restart: unless-stopped
    image: ghcr.io/alexta69/metube
    ports:
      - '8082:8081'
    volumes:
      - /mnt/storage/torrents/metube:/data
      - /opt/config/metube:/config
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'Europe/Stockholm'
      UMASK: '002'
      DARK_MODE: 'true'
      DOWNLOAD_DIR: '/data'
      AUDIO_DOWNLOAD_DIR: '/data/mp3'
      #- YTDL_OPTIONS= #optional
    networks:
      - docker_default
networks:
  docker_default:
    external: true
