services:
  prowlarr-whisparr:
    container_name: prowlarr-whispar
    image: ghcr.io/hotio/prowlarr
    networks:
      - docker_default
    ports:
      - "9695:9696"
    environment:
      PUID: '$PUID'
      PGID: '$PGID'
      UMASK: '$UMASK'
      TZ: '$TZ'
    volumes:
      - '$WORKDIR/prowlarr-whispar:/config'
      - '$DATADIR'

networks:
  docker_default:
    external: true
    
