services:
  prowlarr-whisparr:
    container_name: prowlarr-whispar
    image: ghcr.io/hotio/prowlarr
    networks:
      - docker_default
    ports:
      - "9695:9696"
    environment:
      PUID: '1000'
      PGID: '1000'
      UMASK: '002'
      TZ: 'Europe/Stockholm'
    volumes:
      - /opt/config/prowlarr-whispar:/config

networks:
  docker_default:
    external: true
    
