services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    networks:
      - docker_default
    ports:
      - "8989:8989"
    environment:
      PUID: '$PUID'
      PGID: '$PGID'
      UMASK: '$UMASK'
      TZ: '$TZ'
    volumes:
      - '$WORKDIR/sonarr:/config'
      - '$DATADIR'

networks:
  docker_default:
    external: true
