services:
  radarrhd:
    container_name: radarrhd
    image: ghcr.io/hotio/radarr
    networks:
      - docker_default
    ports:
      - "7878:7878"
    environment:
      PUID: '$PUID'
      PGID: '$PGID'
      UMASK: '$UMASK'
      TZ: '$TZ'
    volumes:
      - '$WORKDIR/radarrhd:/config'
      - '$DATADIR'

networks:
  docker_default:
    external: true
