services:
  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      - docker_default
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "npmdb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /opt/config/npm/data:/data
      - /opt/config/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - npmdb

  npmdb:
    container_name: npmdb
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    networks:
      - docker_default
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - /opt/config/npm/mysql:/var/lib/mysql

networks:
  docker_default:
    external: true
    
