services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    networks:
      - docker_default
    ports:
      - "6969:6969"
    environment:
      PUID: '$PUID'
      PGID: '$PGID'
      UMASK: '$UMASK'
      TZ: '$TZ'
    volumes:
      - '$WORKDIR/whisparr:/config'
      - '$DATADIR'

networks:
  docker_default:
    external: true
