services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    networks:
      - docker_default
    ports:
      - "6969:6969"
    environment:
      PUID: '1000'
      PGID: '1000'
      UMASK: '002'
      TZ: 'Europe/Stockholm'
    volumes:
      - /opt/config/whisparr:/config
      - /mnt:/mnt

networks:
  docker_default:
    external: true
