services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    networks:
      - docker_default
    ports:
      - '9117:9117'
    volumes:
      - /opt/config/jackett:/config
      - /mnt:/mnt
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: 'Europe/Stockholm''
      PUID: '1000'
      PGID: '1000'
      AUTO_UPDATE: 'true' #optional
      RUN_OPTS: '' #optional

networks:
  docker_default:
    external: true
