services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PUID: '$PUID'
      PGID: '$PGID'
      UMASK: '$UMASK'
      TZ: '$TZ'
      WEBUI_PORT: '8083'
      TORRENTING_PORT: '6881'
    volumes:
      - '$WORKDIR/qbittorrent:/config'
      - '$DATADIR2/storage/torrents:/downloads'
    networks:
      - docker_default
    ports:
      - 8083:8083
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    
networks:
  docker_default:
    external: true
