services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    networks:
      - docker_default
    ports:
      - "9696:9696"
    environment:
      PUID: '1000'
      PGID: '1000'
      UMASK: '002'
      TZ: 'Europe/Stockholm'
    volumes:
      - /opt/config/prowlarr:/config
      - ./Custom:/config/Definitions/Custom

networks:
  docker_default:
    external: true
